hystrix.command.fallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000



spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order-service
        uri: lb://order-service
        predicates:
        - Path=/order/**

      - id: product-service
        uri: lb://product-service
        predicates:
        - Path=/product/**



server:
  port: 8887

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

